//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hk4tech_picture_viewer.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hk4tech_picture_viewer.languages.lang_ar", typeof(lang_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن البرنامج.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الملفات.
        /// </summary>
        public static string all_files {
            get {
                return ResourceManager.GetString("all-files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع تنسيقات الصور.
        /// </summary>
        public static string all_image_formats {
            get {
                return ResourceManager.GetString("all-image-formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دائمًا في المقدمة.
        /// </summary>
        public static string always_on_top {
            get {
                return ResourceManager.GetString("always-on-top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عارض صور سطح المكتب خفيف الوزن ومتعدد الاستخدامات لنظام التشغيل Windows. أفضل بديل لعارض صور Windows الافتراضي..
        /// </summary>
        public static string app_description {
            get {
                return ResourceManager.GetString("app-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التطبيق محدث!.
        /// </summary>
        public static string app_is_up_to_date {
            get {
                return ResourceManager.GetString("app-is-up-to-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراءات بدء تشغيل التطبيق.
        /// </summary>
        public static string app_startup_actions {
            get {
                return ResourceManager.GetString("app-startup-actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبة أبعاد.
        /// </summary>
        public static string aspect_ratio {
            get {
                return ResourceManager.GetString("aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلقائي.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم التلقائي.
        /// </summary>
        public static string auto_size {
            get {
                return ResourceManager.GetString("auto-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكبير تلقائي.
        /// </summary>
        public static string auto_zoom {
            get {
                return ResourceManager.GetString("auto-zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لون الخلفية.
        /// </summary>
        public static string background_color {
            get {
                return ResourceManager.GetString("background-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسفل.
        /// </summary>
        public static string bottom {
            get {
                return ResourceManager.GetString("bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفح.
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفح باستخدام عارض الصور HK4TECH.
        /// </summary>
        public static string browse_folder_with_qpv {
            get {
                return ResourceManager.GetString("browse-folder-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصفح بحثًا عن الإضافات.
        /// </summary>
        public static string browse_for_plugins {
            get {
                return ResourceManager.GetString("browse-for-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسط.
        /// </summary>
        public static string center {
            get {
                return ResourceManager.GetString("center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة بالوسط.
        /// </summary>
        public static string center_image {
            get {
                return ResourceManager.GetString("center-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنتيمترات.
        /// </summary>
        public static string centimeters {
            get {
                return ResourceManager.GetString("centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير عتامة النافذة.
        /// </summary>
        public static string change_window_opacity {
            get {
                return ResourceManager.GetString("change-window-opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق من وجود تحديثات التطبيق.
        /// </summary>
        public static string check_for_app_updates {
            get {
                return ResourceManager.GetString("check-for-app-updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلفية الشطرنج.
        /// </summary>
        public static string checkboard_background {
            get {
                return ResourceManager.GetString("checkboard-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر اللون.
        /// </summary>
        public static string choose_color {
            get {
                return ResourceManager.GetString("choose-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر مقاسًا مناسبًا.
        /// </summary>
        public static string choose_fit {
            get {
                return ResourceManager.GetString("choose-fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظف.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاصلة.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضغط.
        /// </summary>
        public static string compression {
            get {
                return ResourceManager.GetString("compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة السياق.
        /// </summary>
        public static string context_menu {
            get {
                return ResourceManager.GetString("context-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لتغيير خيارات قائمة السياق ، تحتاج إلى تشغيل التطبيق مع المسؤول.
        /// </summary>
        public static string context_menu_notice {
            get {
                return ResourceManager.GetString("context-menu-notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ الملف الأصلي.
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ الصورة.
        /// </summary>
        public static string copy_image {
            get {
                return ResourceManager.GetString("copy-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاؤه.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاؤه بواسطة.
        /// </summary>
        public static string created_by {
            get {
                return ResourceManager.GetString("created-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قص.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر العثور على الملف الحالي.
        /// </summary>
        public static string cur_file_not_found {
            get {
                return ResourceManager.GetString("cur-file-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قص.
        /// </summary>
        public static string cut {
            get {
                return ResourceManager.GetString("cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داكن.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الملف.
        /// </summary>
        public static string delete_file {
            get {
                return ResourceManager.GetString("delete-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الاضافة.
        /// </summary>
        public static string delete_plugin {
            get {
                return ResourceManager.GetString("delete-plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد إزالة المكون الإضافي؟.
        /// </summary>
        public static string delete_plugin_warning {
            get {
                return ResourceManager.GetString("delete-plugin-warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string desc {
            get {
                return ResourceManager.GetString("desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم القرص.
        /// </summary>
        public static string disk_size {
            get {
                return ResourceManager.GetString("disk-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تحفظ.
        /// </summary>
        public static string dont_save {
            get {
                return ResourceManager.GetString("dont-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل التحديث....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة المسحوبة.
        /// </summary>
        public static string dragged_image {
            get {
                return ResourceManager.GetString("dragged-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصورة.
        /// </summary>
        public static string edit_image {
            get {
                return ResourceManager.GetString("edit-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحرير منطقة التحديد.
        /// </summary>
        public static string edit_selection {
            get {
                return ResourceManager.GetString("edit-selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأثيرات.
        /// </summary>
        public static string effects {
            get {
                return ResourceManager.GetString("effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط على {0} للخروج من التطبيق.
        /// </summary>
        public static string esc_to_exit {
            get {
                return ResourceManager.GetString("esc-to-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخرج من وضع صورة داخل صورة.
        /// </summary>
        public static string exit_picture_in_picture {
            get {
                return ResourceManager.GetString("exit-picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إمتداد.
        /// </summary>
        public static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التطبيق الخارجي المفضل.
        /// </summary>
        public static string fav_external_app {
            get {
                return ResourceManager.GetString("fav-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نسخ الملف إلى الحافظة.
        /// </summary>
        public static string file_copied_to_clipboard {
            get {
                return ResourceManager.GetString("file-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نقل الملف إلى سلة المحذوفات.
        /// </summary>
        public static string file_moved_to_trash {
            get {
                return ResourceManager.GetString("file-moved-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصائص الملف.
        /// </summary>
        public static string file_properties {
            get {
                return ResourceManager.GetString("file-properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعيد تحميل الملف.
        /// </summary>
        public static string file_reloaded {
            get {
                return ResourceManager.GetString("file-reloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملء.
        /// </summary>
        public static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملائم.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انعكاس أفقي.
        /// </summary>
        public static string flip_horizontal {
            get {
                return ResourceManager.GetString("flip-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انعكاس عمودي.
        /// </summary>
        public static string flip_vertical {
            get {
                return ResourceManager.GetString("flip-vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلد.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوضع بدون إطار.
        /// </summary>
        public static string frameless_mode {
            get {
                return ResourceManager.GetString("frameless-mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الحافظة.
        /// </summary>
        public static string from_clipboard {
            get {
                return ResourceManager.GetString("from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من &quot;{0}&quot;.
        /// </summary>
        public static string from_format {
            get {
                return ResourceManager.GetString("from-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار الكامل.
        /// </summary>
        public static string full_path {
            get {
                return ResourceManager.GetString("full-path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاشة كاملة.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المؤشر في وضع ملء الشاشة.
        /// </summary>
        public static string fullscreen_cursor {
            get {
                return ResourceManager.GetString("fullscreen-cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعدنا في ترجمة هذا التطبيق.
        /// </summary>
        public static string help_us_translate_app {
            get {
                return ResourceManager.GetString("help-us-translate-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم نسخ الصورة إلى الحافظة.
        /// </summary>
        public static string image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("image-copied-to-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الصورة.
        /// </summary>
        public static string image_info {
            get {
                return ResourceManager.GetString("image-info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم لصق الصورة من الحافظة.
        /// </summary>
        public static string image_pasted_from_clipboard {
            get {
                return ResourceManager.GetString("image-pasted-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوصة.
        /// </summary>
        public static string inches {
            get {
                return ResourceManager.GetString("inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الماوس ولوحة المفاتيح.
        /// </summary>
        public static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تثبيت الآن.
        /// </summary>
        public static string install_now {
            get {
                return ResourceManager.GetString("install-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفقي.
        /// </summary>
        public static string landscape {
            get {
                return ResourceManager.GetString("landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفقي.
        /// </summary>
        public static string landscape_orientation {
            get {
                return ResourceManager.GetString("landscape-orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليسار.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السهم الايسر.
        /// </summary>
        public static string left_arrow {
            get {
                return ResourceManager.GetString("left-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مضئ.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضْع.
        /// </summary>
        public static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحفاظ على نسبة العرض إلى الارتفاع.
        /// </summary>
        public static string maintain_aspect_ratio {
            get {
                return ResourceManager.GetString("maintain-aspect-ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدود الهامش.
        /// </summary>
        public static string margin_bounds {
            get {
                return ResourceManager.GetString("margin-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهوامش.
        /// </summary>
        public static string margins {
            get {
                return ResourceManager.GetString("margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميغا بكسل.
        /// </summary>
        public static string megapixels {
            get {
                return ResourceManager.GetString("megapixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الذاكرة.
        /// </summary>
        public static string memory_error {
            get {
                return ResourceManager.GetString("memory-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناقص.
        /// </summary>
        public static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل.
        /// </summary>
        public static string modified {
            get {
                return ResourceManager.GetString("modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الخيارات.
        /// </summary>
        public static string more_options {
            get {
                return ResourceManager.GetString("more-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الإضافات.
        /// </summary>
        public static string more_plugins {
            get {
                return ResourceManager.GetString("more-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمل تمرير عجلة الماوس.
        /// </summary>
        public static string mouse_wheel_action {
            get {
                return ResourceManager.GetString("mouse-wheel-action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقل الملف إلى سلة المحذوفات.
        /// </summary>
        public static string move_to_trash {
            get {
                return ResourceManager.GetString("move-to-trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخة جديدة متاحة!.
        /// </summary>
        public static string new_version_available {
            get {
                return ResourceManager.GetString("new-version-available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نافذة جديدة.
        /// </summary>
        public static string new_window {
            get {
                return ResourceManager.GetString("new-window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء نافذة فارغة جديدة.
        /// </summary>
        public static string new_window_desc {
            get {
                return ResourceManager.GetString("new-window-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة التالية في المجلد.
        /// </summary>
        public static string next_image {
            get {
                return ResourceManager.GetString("next-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة التالية بعد 1 ثانية.
        /// </summary>
        public static string next_image_in_1_second {
            get {
                return ResourceManager.GetString("next-image-in-1-second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة التالية في غضون {0} ثانية.
        /// </summary>
        public static string next_image_in_x_seconds {
            get {
                return ResourceManager.GetString("next-image-in-x-seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة التالية / السابقة في المجلد.
        /// </summary>
        public static string next_prev_image {
            get {
                return ResourceManager.GetString("next-prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملف.
        /// </summary>
        public static string no_file {
            get {
                return ResourceManager.GetString("no-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد ملفات لفتحها.
        /// </summary>
        public static string no_files_to_open {
            get {
                return ResourceManager.GetString("no-files-to-open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظها.
        /// </summary>
        public static string not_saved {
            get {
                return ResourceManager.GetString("not-saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتح الملف باستخدام تطبيق خارجي.
        /// </summary>
        public static string open_external {
            get {
                return ResourceManager.GetString("open-external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتح الملف.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتح المجلد.
        /// </summary>
        public static string open_folder {
            get {
                return ResourceManager.GetString("open-folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتح المجلد تكراريًا.
        /// </summary>
        public static string open_recursive {
            get {
                return ResourceManager.GetString("open-recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح باستخدام.
        /// </summary>
        public static string open_with {
            get {
                return ResourceManager.GetString("open-with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر تطبيقًا لفتحه.
        /// </summary>
        public static string open_with_choose {
            get {
                return ResourceManager.GetString("open-with-choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح باستخدام تطبيق مخصص.
        /// </summary>
        public static string open_with_custom {
            get {
                return ResourceManager.GetString("open-with-custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح مع التطبيق الافتراضي.
        /// </summary>
        public static string open_with_default {
            get {
                return ResourceManager.GetString("open-with-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتح باستخدام عارض الصور HK4TECH.
        /// </summary>
        public static string open_with_qpv {
            get {
                return ResourceManager.GetString("open-with-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم الأصلي.
        /// </summary>
        public static string original_size {
            get {
                return ResourceManager.GetString("original-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لصق من الحافظة.
        /// </summary>
        public static string paste_from_clipboard {
            get {
                return ResourceManager.GetString("paste-from-clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصق الصورة.
        /// </summary>
        public static string paste_image {
            get {
                return ResourceManager.GetString("paste-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الملف نهائيا.
        /// </summary>
        public static string perm_delete {
            get {
                return ResourceManager.GetString("perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع صورة داخل صورة.
        /// </summary>
        public static string picture_in_picture {
            get {
                return ResourceManager.GetString("picture-in-picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بكسل.
        /// </summary>
        public static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء فتح صورة لعرضها أو تحريرها.
        /// </summary>
        public static string please_open_image {
            get {
                return ResourceManager.GetString("please-open-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج المساعد.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير البرنامج المساعد.
        /// </summary>
        public static string plugin_manager {
            get {
                return ResourceManager.GetString("plugin-manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على دليل البرنامج المساعد.
        /// </summary>
        public static string plugin_not_found {
            get {
                return ResourceManager.GetString("plugin-not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع البرنامج المساعد.
        /// </summary>
        public static string plugin_website {
            get {
                return ResourceManager.GetString("plugin-website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالإضافة إلى.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمودي.
        /// </summary>
        public static string portrait {
            get {
                return ResourceManager.GetString("portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسبقة.
        /// </summary>
        public static string presets {
            get {
                return ResourceManager.GetString("presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط على {0} للخروج من وضع ملء الشاشة.
        /// </summary>
        public static string press_to_exit_fullscreen {
            get {
                return ResourceManager.GetString("press-to-exit-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة السابقة في المجلد.
        /// </summary>
        public static string prev_image {
            get {
                return ResourceManager.GetString("prev-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة / تصدير إلى PDF.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادت الطباعة.
        /// </summary>
        public static string print_conf {
            get {
                return ResourceManager.GetString("print-conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر تعيين هوامش المستند.
        /// </summary>
        public static string print_margins_error {
            get {
                return ResourceManager.GetString("print-margins-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الطباعة.
        /// </summary>
        public static string print_size {
            get {
                return ResourceManager.GetString("print-size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاهز للتثبيت.
        /// </summary>
        public static string ready_to_install {
            get {
                return ResourceManager.GetString("ready-to-install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تحميل الملف.
        /// </summary>
        public static string reload_file {
            get {
                return ResourceManager.GetString("reload-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تحميل قائمة الإضافات.
        /// </summary>
        public static string reload_plugins {
            get {
                return ResourceManager.GetString("reload-plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير الحجم SVG.
        /// </summary>
        public static string resize_svg {
            get {
                return ResourceManager.GetString("resize-svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدقة.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تشغيل التطبيق.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب إعادة تشغيل التطبيق.
        /// </summary>
        public static string restart_required {
            get {
                return ResourceManager.GetString("restart-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعادة حدود النافذة الأخيرة.
        /// </summary>
        public static string restore_last_window_bounds {
            get {
                return ResourceManager.GetString("restore-last-window-bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمين.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السهم الأيمن.
        /// </summary>
        public static string right_arrow {
            get {
                return ResourceManager.GetString("right-arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استدارة 180 درجة.
        /// </summary>
        public static string rotate_180 {
            get {
                return ResourceManager.GetString("rotate-180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدوير عكس اتجاه عقارب الساعة.
        /// </summary>
        public static string rotate_left {
            get {
                return ResourceManager.GetString("rotate-left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدوير في اتجاه عقارب الساعة.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate-right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ بأسم.
        /// </summary>
        public static string save_as {
            get {
                return ResourceManager.GetString("save-as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقل لأعلى / لأسفل.
        /// </summary>
        public static string scroll_up_down {
            get {
                return ResourceManager.GetString("scroll-up-down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثواني.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد الكل.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select-all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أداة التحديد.
        /// </summary>
        public static string selection_tool {
            get {
                return ResourceManager.GetString("selection-tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين عارض الصور الافتراضي.
        /// </summary>
        public static string set_as_default_image_viewer {
            get {
                return ResourceManager.GetString("set-as-default-image-viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين كخلفية لسطح المكتب.
        /// </summary>
        public static string set_as_desktop_background {
            get {
                return ResourceManager.GetString("set-as-desktop-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الخلفية.
        /// </summary>
        public static string set_background {
            get {
                return ResourceManager.GetString("set-background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الهوامش.
        /// </summary>
        public static string set_margins_btn {
            get {
                return ResourceManager.GetString("set-margins-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار الملف في Explorer.
        /// </summary>
        public static string show_file_explorer {
            get {
                return ResourceManager.GetString("show-file-explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار أسهم التنقل.
        /// </summary>
        public static string show_nav_arrows {
            get {
                return ResourceManager.GetString("show-nav-arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار عداد عرض الشرائح.
        /// </summary>
        public static string show_slideshow_counter {
            get {
                return ResourceManager.GetString("show-slideshow-counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أظهر شريط الحاله.
        /// </summary>
        public static string show_status_bar {
            get {
                return ResourceManager.GetString("show-status-bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار شريط الأدوات.
        /// </summary>
        public static string show_toolbar {
            get {
                return ResourceManager.GetString("show-toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخطي هذه النسخة.
        /// </summary>
        public static string skip_this_version {
            get {
                return ResourceManager.GetString("skip-this-version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الشرائح.
        /// </summary>
        public static string slideshow {
            get {
                return ResourceManager.GetString("slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتداد.
        /// </summary>
        public static string span {
            get {
                return ResourceManager.GetString("span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مربع.
        /// </summary>
        public static string square {
            get {
                return ResourceManager.GetString("square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدء التشغيل.
        /// </summary>
        public static string startup {
            get {
                return ResourceManager.GetString("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إطالة.
        /// </summary>
        public static string stretch {
            get {
                return ResourceManager.GetString("stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ستفقد جميع البيانات غير المحفوظة. هل أنت متأكد أنك تريد إغلاق التطبيق؟.
        /// </summary>
        public static string sure_close_app {
            get {
                return ResourceManager.GetString("sure-close-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد حذف هذا الملف نهائيًا؟.
        /// </summary>
        public static string sure_perm_delete {
            get {
                return ResourceManager.GetString("sure-perm-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت التبديل.
        /// </summary>
        public static string switching_time {
            get {
                return ResourceManager.GetString("switching-time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مظهر.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجانب.
        /// </summary>
        public static string tile {
            get {
                return ResourceManager.GetString("tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نص.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدوات.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعلى.
        /// </summary>
        public static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترجمة بواسطة.
        /// </summary>
        public static string translated_by {
            get {
                return ResourceManager.GetString("translated-by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخيارات.
        /// </summary>
        public static string type_options {
            get {
                return ResourceManager.GetString("type-options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغة واجهة المستخدم.
        /// </summary>
        public static string ui_lang {
            get {
                return ResourceManager.GetString("ui-lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير قادر على فتح ملف.
        /// </summary>
        public static string unable_open_file {
            get {
                return ResourceManager.GetString("unable-open-file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر فتح الملف ، تم تخطي الملف.
        /// </summary>
        public static string unable_open_file_skipped {
            get {
                return ResourceManager.GetString("unable-open-file-skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر تشغيل التطبيق الخارجي.
        /// </summary>
        public static string unable_to_run_external_app {
            get {
                return ResourceManager.GetString("unable-to-run-external-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التغييرات غير المحفوظة.
        /// </summary>
        public static string unsaved_changes {
            get {
                return ResourceManager.GetString("unsaved-changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الحالية بها تغييرات غير محفوظة. ماذا تريد ان تفعل؟.
        /// </summary>
        public static string unsaved_changes_question {
            get {
                return ResourceManager.GetString("unsaved-changes-question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنسيق بكسل غير مدعوم.
        /// </summary>
        public static string unsupported_pixel_format {
            get {
                return ResourceManager.GetString("unsupported-pixel-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل التحديث.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update-failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتوفر الإصدار {0} من عارض الصور HK4TECH ، هل تستخدم الإصدار {1} ، فهل تريد التحديث الآن؟.
        /// </summary>
        public static string update_text {
            get {
                return ResourceManager.GetString("update-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث عارض الصور HK4TECH.
        /// </summary>
        public static string updating_qpv {
            get {
                return ResourceManager.GetString("updating-qpv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم إعدادات النظام.
        /// </summary>
        public static string use_system_setting {
            get {
                return ResourceManager.GetString("use-system-setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإصدار.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو الجديد؟.
        /// </summary>
        public static string whats_new {
            get {
                return ResourceManager.GetString("whats-new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكبير.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بالتكبير.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكبير / التصغير.
        /// </summary>
        public static string zoom_in_out {
            get {
                return ResourceManager.GetString("zoom-in-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصغير.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكبير الحجم الفعلي.
        /// </summary>
        public static string zoom_to_actual_size {
            get {
                return ResourceManager.GetString("zoom-to-actual-size", resourceCulture);
            }
        }
    }
}
